#!/bin/sh

exec < /dev/tty

message=$(cat $1)
convention='^(feat|fix|refactor|design|doc|test|tools|release|revert)(\([a-z]+\))?!?: .{1,80}'
[[ $message =~ $convention ]] || read -p $'\e[31m✗\e[0m conventional commit, continue anyway ? (Y/n) ' yn
[[ $yn =~ ^(N|n|no)$ ]] && exit
echo $'\e[32m✓\e[0m conventional commit'

exec <&-
